"""Chinese display names extracted from civ6bbg.github.io zh_Hans_CN 7.4 pages."""

from __future__ import annotations

BBG_ZH_NAME_MAP = {
    "AT Crew": "反坦克组",
    "AT_Crew": "反坦克组",
    "Abdus Salam": "阿卜杜勒·萨拉姆",
    "Abraham Lincoln": "亚伯拉罕·林肯",
    "Abu Al Qasim Al Zahrawi": "艾布·卡西姆·扎哈拉维",
    "Acropolis": "卫城",
    "Ada Lovelace": "爱达·勒芙蕾丝",
    "Adam Smith": "亚当·斯密",
    "Adi Shankara": "阿迪·商羯罗",
    "Admiral": "海军统帅",
    "Advanced AI": "高级人工智能",
    "Advanced Ai": "高级人工智能",
    "Advanced Ballistics": "高级弹道学",
    "Advanced Flight": "现代航空",
    "Advanced Power Cells": "高级能量电池",
    "Advanced_AI": "高级人工智能",
    "Advanced_Ballistics": "高级弹道学",
    "Advanced_Flight": "现代航空",
    "Advanced_Power_Cells": "高级能量电池",
    "Aerodrome": "航空港",
    "Aethelflaed": "埃塞尔弗莱德",
    "Agriculture": "农业发展",
    "Ahmad Shah Massoud": "阿哈默德·沙哈·马苏德",
    "Air Defense Initiative": "防空计划",
    "Aircraft Carrier": "航空母舰",
    "Aircraft_Carrier": "航空母舰",
    "Airport": "机场",
    "Airstrip": "飞机跑道",
    "Akkad": "阿卡德",
    "Akkad Frontend": "阿卡德",
    "Alan Turing": "阿兰·图灵",
    "Albert Einstein": "阿尔伯特·爱因斯坦",
    "Alcazar": "阿卡萨城堡",
    "Alcázar": "阿卡萨城堡",
    "Alexander": "亚历山大",
    "Alexander Pushkin": "亚历山大·普希金",
    "Alfred Nobel": "阿尔弗雷德·诺贝尔",
    "Alhambra": "阿尔罕布拉宫",
    "Alvar Aalto": "阿尔瓦·阿尔托",
    "Amani": "阿玛妮",
    "Amanitore": "阿曼妮托尔",
    "Ambassador Affluence": "富裕",
    "Ambassador Foreign Investor": "外国投资者",
    "Ambassador Messenger": "信使",
    "Ambassador Negotiator": "谈判者",
    "Ambassador Puppeteer": "幕后主脑",
    "Ambiorix": "安比奥里克斯",
    "America": "美国",
    "America Abraham Lincoln": "美国 亚伯拉罕·林肯",
    "America Teddy Roosevelt (Bull Moose)": "美国 泰迪·罗斯福（进步党）",
    "America Teddy Roosevelt (Rough Rider)": "美国 泰迪·罗斯福（莽骑兵）",
    "America Teddy Roosevelt (bull Moose)": "美国 泰迪·罗斯福（进步党）",
    "America Teddy Roosevelt (rough Rider)": "美国 泰迪·罗斯福（莽骑兵）",
    "American P51": "P-51战斗机",
    "American Rough Rider": "莽骑兵",
    "Amina": "阿米娜",
    "Amphitheater": "古罗马剧场",
    "Amrita Sher Gil": "阿姆瑞塔·谢吉尔",
    "Amundsen Scott Research Station": "阿蒙森-斯科特南极站",
    "Amundsen-Scott Research Station": "阿蒙森-斯科特南极站",
    "Amundsen-scott Research Station": "阿蒙森-斯科特南极站",
    "Ancestral Hall": "祠堂",
    "Ancient Era": "远古时代",
    "Ancient Walls": "远古城墙",
    "Andrey Rublev": "安德烈·鲁布烈夫",
    "Angelica Kauffman": "安杰丽卡·考夫曼",
    "Angkor Wat": "吴哥窟",
    "Animal Husbandry": "畜牧业",
    "Animal_Husbandry": "畜牧业",
    "Anshan": "安善",
    "Antananarivo": "塔那那利佛",
    "Antananarivo Frontend": "塔那那利佛",
    "Anti Air Gun": "防空炮",
    "Anti Air_Gun": "防空炮",
    "Anti-Air Gun": "防空炮",
    "Anti-Air_Gun": "防空炮",
    "Anti-air Gun": "防空炮",
    "Antiair Gun": "防空炮",
    "Antioch Frontend": "威尼斯",
    "Antonin Dvorak": "安东尼·德沃夏克",
    "Antonio Carlos Gomez": "安东尼奥·卡洛斯·戈梅斯",
    "Antonio Vivaldi": "安东尼奥·维瓦尔第",
    "Apadana": "阿帕达纳宫",
    "Apostle": "使徒",
    "Apprenticeship": "学徒",
    "Aquarium": "水族馆",
    "Aquatics Center": "水上运动中心",
    "Arabia": "阿拉伯",
    "Arabia Saladin (Sultan)": "阿拉伯 萨拉丁（苏丹）",
    "Arabia Saladin (Vizier)": "阿拉伯 萨拉丁（维齐尔）",
    "Arabia Saladin (sultan)": "阿拉伯 萨拉丁（苏丹）",
    "Arabia Saladin (vizier)": "阿拉伯 萨拉丁（维齐尔）",
    "Arabian Mamluk": "奴隶兵",
    "Archaeological Museum": "考古博物馆",
    "Archer": "弓箭手",
    "Archery": "箭术",
    "Arena": "竞技场",
    "Armagh": "阿尔马",
    "Armagh Frontend": "阿尔马",
    "Armory": "兵工厂",
    "Art Museum": "艺术博物馆",
    "Artemisia": "阿尔特米西亚",
    "Artillery": "大炮",
    "Artist": "大艺术家",
    "Aryabhata": "阿耶波多",
    "Astrology": "占星术",
    "Astronomy": "天文学",
    "At Crew": "反坦克组",
    "Atomic Era": "原子能时代",
    "Auckland": "奥克兰",
    "Auckland Frontend": "奥克兰",
    "Audience Chamber": "谒见厅",
    "Australia": "澳大利亚",
    "Australia John Curtin": "澳大利亚 约翰·科廷",
    "Ayutthaya": "阿瑜陀耶",
    "Ayutthaya Frontend": "阿瑜陀耶",
    "Aztec": "阿兹特克",
    "Aztec Eagle Warrior": "雄鹰战士",
    "Aztec Montezuma": "阿兹特克 蒙特祖玛",
    "Babylon Frontend": "安善",
    "Babylon Hammurabi": "巴比伦 汉谟拉比",
    "Babylon Stk": "巴比伦",
    "Babylonian Sabum Kibittum": "主力军团",
    "Ballistics": "弹道学",
    "Bandar Brunei": "斯里巴加湾",
    "Bank": "银行",
    "Banking": "银行业",
    "Barbarossa": "弗雷德里克·巴巴罗萨",
    "Barbary Corsair": "巴巴里海盗",
    "Barbary_Corsair": "巴巴里海盗",
    "Barracks": "兵营",
    "Barringer Crater": "巴林格陨石坑",
    "Basil": "巴兹尔二世",
    "Basilikoi Paides": "皇家学堂",
    "Batey": "巴特依",
    "Bath": "浴场",
    "Battering Ram": "破城槌",
    "Battering_Ram": "破城槌",
    "Battleship": "战舰",
    "Beach Resort": "海滨度假区",
    "Beatrix Potter": "碧雅翠丝·波特",
    "Bermuda Triangle": "百慕大三角区",
    "Berserker": "狂暴武士",
    "Bhasa": "跋娑",
    "Bi Sheng": "毕昇",
    "Big Ben": "大本钟",
    "Bioluminescent Bay": "生物荧光海湾",
    "Biosphere": "生物圈",
    "Biosphère": "生物圈",
    "Biplane": "双翼机",
    "Bireme": "双层桨座战船",
    "Black Army": "黑军",
    "Black_Army": "黑军",
    "Bodhidharma": "菩提达摩",
    "Bologna": "博洛尼亚",
    "Bologna Frontend": "博洛尼亚",
    "Bolshoi Theatre": "莫斯科大剧院",
    "Bombard": "射石炮",
    "Bomber": "轰炸机",
    "Boris Orlovsky": "鲍里斯·奥洛夫斯基",
    "Boudica": "布狄卡",
    "Brazil": "巴西",
    "Brazil Pedro II": "巴西 佩德罗二世",
    "Brazilian Minas Geraes": "米纳斯吉拉斯",
    "Broadcast Center": "广播中心",
    "Broadway": "百老汇",
    "Bronze Working": "铸铜术",
    "Bronze_Working": "铸铜术",
    "Brussels": "布鲁塞尔",
    "Buenos Aires": "布宜诺斯艾利斯",
    "Builder Guildmaster": "公会首领",
    "Building Lime Phoe Ahiram Tomb": "皇家陵墓",
    "Buttress": "扶壁",
    "Byzantine Dromon": "火战船",
    "Byzantine Tagma": "甲胄骑兵",
    "Byzantium": "拜占庭",
    "Byzantium Basil II": "拜占庭 巴兹尔二世",
    "Byzantium Theodora": "拜占庭 狄奥多拉",
    "Caguana": "卡瓜纳",
    "Caguana Frontend": "卡瓜纳",
    "Cahokia": "卡霍基亚",
    "Cahokia Frontend": "卡霍基亚",
    "Cahokia Mounds": "卡霍基亚土墩",
    "Camp": "营地",
    "Campus": "学院",
    "Canada": "加拿大",
    "Canada Mountie": "皇家骑警",
    "Canada Wilfrid Laurier": "加拿大 威尔弗里德·劳雷尔",
    "Capitalism": "资本主义",
    "Capou Agha": "卡普阿迦",
    "Caravel": "轻快帆船",
    "Cardiff": "加的夫",
    "Cardiff Frontend": "加的夫",
    "Cardinal Bishop": "大主教",
    "Cardinal Citadel God": "神之堡垒",
    "Cardinal Citadel Of God": "神之堡垒",
    "Cardinal Divine Architect": "神圣建筑师",
    "Cardinal Patron Saint": "主保圣人",
    "Carl Sagan": "卡尔·萨根",
    "Carolean": "卡洛林步兵",
    "Cartography": "制图学",
    "Casa De Contratacion": "西印度交易所",
    "Casa de Contratacion": "西印度交易所",
    "Casa de Contratación": "西印度交易所",
    "Castle": "中世纪城墙",
    "Castles": "城堡",
    "Catapult": "石弩",
    "Cathedral": "大教堂",
    "Catherine De Medici Alt": "凯瑟琳·德·美第奇（寻欢作乐）",
    "Catherine De Medici Expanded": "凯瑟琳·德·美第奇（黑王后）",
    "Cavalry": "骑兵",
    "Celestial Navigation": "天文导航",
    "Celestial_Navigation": "天文导航",
    "Cerro De Potosi": "富饶山",
    "Cerro de Potosi": "富饶山",
    "Chancery": "外交办",
    "Chandragupta": "旃陀罗笈多",
    "Charles Correa": "查尔斯·柯里亚",
    "Charles Darwin": "查尔斯·达尔文",
    "Chateau": "城堡",
    "Chemamull": "马普切木人",
    "Chemistry": "化学",
    "Chester Nimitz": "切斯特·尼米兹",
    "Chichen Itza": "奇琴伊察",
    "China": "中国",
    "China Kublai Khan (China)": "中国 忽必烈（中国）",
    "China Kublai Khan (china)": "中国 忽必烈（中国）",
    "China Qin (Mandate of Heaven)": "中国 秦始皇（天命者）",
    "China Qin (Unifier)": "中国 秦始皇（大一统）",
    "China Qin (mandate Heaven)": "中国 秦始皇（天命者）",
    "China Qin (mandate Of Heaven)": "中国 秦始皇（天命者）",
    "China Qin (unifier)": "中国 秦始皇（大一统）",
    "China Wu Zetian": "中国 武则天",
    "China Yongle": "中国 永乐皇帝",
    "Chinese Crouching Tiger": "虎蹲炮",
    "Ching Shih": "郑一嫂",
    "Chinguetti": "欣盖提",
    "Chinguetti Frontend": "欣盖提",
    "Chocolate Hills": "巧克力山",
    "Choral Music": "合唱圣歌",
    "Château": "城堡",
    "City Center": "市中心",
    "City Park": "市立公园",
    "City Patron Goddess": "城市守护女神",
    "Civil Engineering": "土木工程",
    "Civil Service": "行政部门",
    "Civil_Engineering": "土木工程",
    "Civil_Service": "行政部门",
    "Clancy Fernando": "克兰西·费尔南多",
    "Clara Schumann": "克拉拉·舒曼",
    "Class Struggle": "阶级斗争",
    "Class_Struggle": "阶级斗争",
    "Classical Era": "古典时期",
    "Claude Monet": "克劳德·莫奈",
    "Cleopatra Alt": "克利欧佩特拉（托勒密）",
    "Cleopatra Original": "克利欧佩特拉（埃及）",
    "Cliffs Dover": "多佛白崖",
    "Cliffs Of Dover": "多佛白崖",
    "Cliffs of Dover": "多佛白崖",
    "Coal Power Plant": "燃煤发电厂",
    "Code Laws": "法典",
    "Code Of Laws": "法典",
    "Code of Laws": "法典",
    "Code_of_Laws": "法典",
    "Colaeus": "柯莱欧司",
    "Cold War": "冷战",
    "Cold_War": "冷战",
    "Colombian Llanero": "牛仔骑兵",
    "Colonialism": "殖民主义",
    "Colossal Head": "巨神头像",
    "Colosseum": "罗马斗兽场",
    "Colossus": "巨像",
    "Comandante General": "总指挥",
    "Combined Arms": "联合作战",
    "Combined_Arms": "联合作战",
    "Combustion": "内燃机",
    "Commandante Antonio Paez": "何塞·安东尼奥·派斯",
    "Commandante Jose De Sucre": "安东尼奥·何塞·苏克雷",
    "Commandante Macgregor": "格雷格尔·麦克格雷格尔",
    "Commandante Marino": "圣地亚哥·马里诺",
    "Commandante Montilla": "马里亚诺·蒙蒂勒",
    "Commandante Narino": "安东尼奥·纳里诺",
    "Commandante Paula Santander": "弗朗西斯科·德保拉·桑坦德尔",
    "Commandante Piar": "曼努埃尔·皮亚尔",
    "Commandante Ribas": "何塞·菲利克斯·里巴斯",
    "Commandante Urdaneta": "拉斐尔·乌达内塔",
    "Commercial Hub": "商业中心",
    "Composites": "复合材料",
    "Computers": "电脑",
    "Confucius": "孔子",
    "Conquistador": "征服者",
    "Conservation": "保护地球",
    "Construction": "建造",
    "Consulate": "领事馆",
    "Copacabana": "科帕卡瓦纳",
    "Corporate Libertarianism": "政治冒险",
    "Cossack": "哥萨克骑兵",
    "Cothon": "U型港",
    "Courser": "追猎者",
    "Craftsmanship": "技艺",
    "Crater Lake": "火山口湖",
    "Cree": "克里",
    "Cree Okihtcitaw": "奥克奇塔乌",
    "Cree Poundmaker": "克里 庞德梅克",
    "Cristo Redentor": "救世基督像",
    "Cross Cultural Dialogue": "跨文化对话",
    "Crossbowman": "弩手",
    "Crouching Tiger": "虎蹲炮",
    "Crouching_Tiger": "虎蹲炮",
    "Cuirassier": "胸甲骑兵",
    "Cultural Hegemony": "文化霸权",
    "Cultural Heritage": "文化遗产",
    "Cultural_Hegemony": "文化霸权",
    "Cultural_Heritage": "文化遗产",
    "Currency": "货币",
    "Cybernetics": "控制论",
    "Cyrus": "居鲁士",
    "Dallol": "达洛尔火山",
    "Dam": "堤坝",
    "Dance Of Aurora": "极光之舞",
    "Dance Of The Aurora": "极光之舞",
    "Dance The Aurora": "极光之舞",
    "Dance of the Aurora": "极光之舞",
    "Dandara": "丹达拉",
    "Dar E Mehr": "拜火神庙",
    "Dar e Mehr": "拜火神庙",
    "Dar-e Mehr": "拜火神庙",
    "De Zeven Provincien": "七省级护卫舰",
    "De Zeven Provinciën": "七省级护卫舰",
    "De_Zeven_Provincien": "七省级护卫舰",
    "De_Zeven_Provinciën": "七省级护卫舰",
    "Dead Sea": "死海",
    "Defender Faith": "信仰护卫者",
    "Defender Of Faith": "信仰护卫者",
    "Defense Logistics": "城防后勤",
    "Defensive Tactics": "防御战术",
    "Defensive_Tactics": "防御战术",
    "Delicate Arch": "精致拱门",
    "Desert Folklore": "沙漠民俗",
    "Destroyer": "驱逐舰",
    "Dido": "狄多",
    "Digger": "矿工军团",
    "Digital Democracy": "分散式主权",
    "Dimitrie Cantemir": "迪米特里·坎特米尔",
    "Diplomatic Quarter": "外交区",
    "Diplomatic Service": "外交部门",
    "Diplomatic_Service": "外交部门",
    "Distributed Sovereignty": "分散式主权",
    "Distributed_Sovereignty": "分散式主权",
    "Divine Inspiration": "神灵的启示",
    "Divine Right": "王权神授",
    "Divine Spark": "神圣之光",
    "Divine_Right": "王权神授",
    "Dmitri Mendeleev": "德米特里·门捷列夫",
    "Dogsled Hunter": "雪橇猎人",
    "Dogsled_Hunter": "雪橇猎人",
    "Domrey": "高棉战象",
    "Donatello": "多纳泰罗",
    "Douglas Macarthur": "道格拉斯·麦克阿瑟",
    "Drama And Poetry": "戏剧和诗歌",
    "Drama Poetry": "戏剧和诗歌",
    "Drama and Poetry": "戏剧和诗歌",
    "Drama_and_Poetry": "戏剧和诗歌",
    "Dromon": "火战船",
    "Drone": "无人机",
    "Dwight Eisenhower": "德怀特·艾森豪威尔",
    "Dzong": "宗堡",
    "Eagle Warrior": "雄鹰战士",
    "Eagle_Warrior": "雄鹰战士",
    "Early Empire": "帝国初期",
    "Early_Empire": "帝国初期",
    "Earth Goddess": "大地女神",
    "Economics": "经济",
    "Edgar Allen Poe": "埃德加·艾伦·坡",
    "Edmonia Lewis": "爱慕妮亚·刘易斯",
    "Education": "教育",
    "Educator Arms Race Proponent": "军备竞赛倡导者",
    "Educator Connoisseur": "鉴赏家",
    "Educator Eureka": "尤里卡",
    "Educator Grants": "拨款",
    "Educator Knowledge": "共享知识",
    "Educator Librarian": "图书馆员",
    "Educator Researcher": "研究员",
    "Educator Space Initiative": "太空计划",
    "Egypt": "埃及",
    "Egypt Cleopatra (Egyptian)": "埃及 克利欧佩特拉（埃及）",
    "Egypt Cleopatra (Ptolemaic)": "埃及 克利欧佩特拉（托勒密）",
    "Egypt Cleopatra (egyptian)": "埃及 克利欧佩特拉（埃及）",
    "Egypt Cleopatra (ptolemaic)": "埃及 克利欧佩特拉（托勒密）",
    "Egypt Ramses II": "埃及 拉美西斯二世",
    "Egyptian Chariot Archer": "世袭贵族战车射手",
    "Ehuatl Wearer": "羽甲战士",
    "Ehuatl_Wearer": "羽甲战士",
    "Eiffel Tower": "埃菲尔铁塔",
    "El Cid": "艾尔·熙德",
    "El Greco": "埃尔·格列柯",
    "Eleanor": "阿基坦的埃莉诺（英国）",
    "Eleanor France": "阿基坦的埃莉诺（法国）",
    "Electricity": "电力",
    "Electronics Factory": "电子厂",
    "Elizabeth": "伊丽莎白一世",
    "Embrasure": "射击孔",
    "Emilie Du Chatelet": "埃米莉·夏特莱",
    "Emily Dickinson": "艾米莉·狄金森",
    "Encampment": "军营",
    "Engineer": "大工程师",
    "Engineering": "工程",
    "England": "英国",
    "England Eleanor Aquitaine (england)": "英国 阿基坦的埃莉诺（英国）",
    "England Eleanor Of Aquitaine (england)": "英国 阿基坦的埃莉诺（英国）",
    "England Eleanor of Aquitaine (England)": "英国 阿基坦的埃莉诺（英国）",
    "England Elizabeth I": "英国 伊丽莎白一世",
    "England Victoria (Age of Empire)": "英国 维多利亚（帝国时代）",
    "England Victoria (Age of Steam)": "英国 维多利亚（蒸汽时代）",
    "England Victoria (age Empire)": "英国 维多利亚（帝国时代）",
    "England Victoria (age Of Empire)": "英国 维多利亚（帝国时代）",
    "England Victoria (age Of Steam)": "英国 维多利亚（蒸汽时代）",
    "England Victoria (age Steam)": "英国 维多利亚（蒸汽时代）",
    "English Redcoat": "红衫军",
    "English Seadog": "海猎犬",
    "Entertainment Complex": "娱乐中心",
    "Environmentalism": "环境保护主义",
    "Erwin Schrodinger": "埃尔文·薛定谔",
    "Estadio Do Maracana": "马拉卡纳体育场",
    "Estadio do Maracana": "马拉卡纳体育场",
    "Estádio do Maracanã": "马拉卡纳体育场",
    "Etemenanki": "埃特曼安吉神庙",
    "Ethiopia": "埃塞俄比亚",
    "Ethiopia Menelik II": "埃塞俄比亚 孟尼利克二世",
    "Ethiopian Oromo Cavalry": "奥罗莫骑兵",
    "Euclid": "欧几里得",
    "Exodus Imperative": "必要性远征",
    "Exodus_Imperative": "必要性远征",
    "Exploration": "探索",
    "Eye Of Sahara": "撒哈拉之眼",
    "Eye Of The Sahara": "撒哈拉之眼",
    "Eye The Sahara": "撒哈拉之眼",
    "Eye of the Sahara": "撒哈拉之眼",
    "Eyjafjallajokull": "艾雅法拉火山",
    "Eyjafjallajökull": "艾雅法拉火山",
    "F Scott Fitzgerald": "弗朗西斯·斯科特·菲茨杰拉德",
    "Factory": "工厂",
    "Farm": "农场",
    "Feed The World": "哺育世界",
    "Feed World": "哺育世界",
    "Feitoria": "商站",
    "Ferdinand Magellan": "斐迪南·麦哲伦",
    "Ferris Wheel": "摩天轮",
    "Fertility Rites": "丰产仪式",
    "Feudalism": "封建主义",
    "Fez": "非斯",
    "Fez Frontend": "非斯",
    "Field Cannon": "野战加农炮",
    "Field_Cannon": "野战加农炮",
    "Fighter": "战斗机",
    "Filippo Brunelleschi": "菲利波·布鲁内列斯基",
    "Film Studio": "电影制片厂",
    "Fire Goddess": "火之女神",
    "Fire Is Born": "西雅赫·卡克",
    "Fire is Born": "西雅赫·卡克",
    "Fishery": "渔场",
    "Fishing Boats": "渔船",
    "Flight": "飞行",
    "Flood Barrier": "拦洪坝",
    "Food Market": "食品市场",
    "Forbidden City": "紫禁城",
    "Foreign Ministry": "外交部",
    "Foreign Trade": "对外贸易",
    "Foreign_Trade": "对外贸易",
    "Fort": "堡垒",
    "Fossil Fuel Power Plant": "燃油发电厂",
    "Fountain Of Youth": "青春之泉",
    "Fountain Youth": "青春之泉",
    "Fountain of Youth": "青春之泉",
    "France": "法国",
    "France Catherine De Medici (black Queen)": "法国 凯瑟琳·德·美第奇（黑王后）",
    "France Catherine De Medici (magnificence)": "法国 凯瑟琳·德·美第奇（寻欢作乐）",
    "France Catherine de Medici (Black Queen)": "法国 凯瑟琳·德·美第奇（黑王后）",
    "France Catherine de Medici (Magnificence)": "法国 凯瑟琳·德·美第奇（寻欢作乐）",
    "France Eleanor Aquitaine (france)": "法国 阿基坦的埃莉诺（法国）",
    "France Eleanor Of Aquitaine (france)": "法国 阿基坦的埃莉诺（法国）",
    "France Eleanor of Aquitaine (France)": "法国 阿基坦的埃莉诺（法国）",
    "Francis Assisi": "阿西西的方济各",
    "Francis Drake": "弗朗西斯·德瑞克",
    "Francis Of Assisi": "阿西西的方济各",
    "Franz Liszt": "弗朗兹·李斯特",
    "Franz Von Hipper": "弗兰兹·冯·希佩尔",
    "Frederic Chopin": "弗里德里克·肖邦",
    "French Garde Imperiale": "帝国卫队",
    "Frigate": "护卫舰",
    "Future Civic": "未来市政",
    "Future Era": "未来时代",
    "Future Tech": "未来科技",
    "Future_Civic": "未来市政",
    "Future_Tech": "未来科技",
    "Gabriela Mistral": "加夫列拉·米斯特拉尔",
    "Gaesatae": "高卢枪佣兵",
    "Gaius Duilius": "盖尤斯·杜伊路斯",
    "Galapagos Islands": "加拉帕戈斯群岛",
    "Galileo Galilei": "伽利略·伽利雷",
    "Galley": "桨帆船",
    "Galápagos Islands": "加拉帕戈斯群岛",
    "Games And Recreation": "游戏和娱乐",
    "Games Recreation": "游戏和娱乐",
    "Games and Recreation": "游戏和娱乐",
    "Games_and_Recreation": "游戏和娱乐",
    "Gandhi": "甘地",
    "Garde Imperiale": "帝国卫队",
    "Garde Impériale": "帝国卫队",
    "Garde_Imperiale": "帝国卫队",
    "Garde_Impériale": "帝国卫队",
    "Garrison Commander": "驻军司令",
    "Gauhar Jaan": "高哈尔·扬",
    "Gaul": "高卢",
    "Gaul Ambiorix": "高卢 安比奥里克斯",
    "Gaul Gaesatae": "高卢枪佣兵",
    "Gaul Vercingetorix": "高卢 维钦托利",
    "General": "大将军",
    "Geneva": "日内瓦",
    "Genghis Khan": "成吉思汗",
    "Geoffrey Chaucer": "杰弗里·乔叟",
    "Georgia": "格鲁吉亚",
    "Georgia Tamar": "格鲁吉亚 塔玛丽",
    "Georgian Khevsureti": "赫雷苏维季战士",
    "Georgy Zhukov": "格奥尔吉·朱可夫",
    "Geothermal Plant": "地热发电厂",
    "German Panzer": "虎式坦克",
    "German Uboat": "U型潜水艇",
    "Germany": "德国",
    "Germany Frederick Barbarossa": "德国 弗雷德里克·巴巴罗萨",
    "Germany Ludwig II": "德国 路德维希二世",
    "Giant Death Robot": "末日机甲",
    "Giant S Causeway": "巨人堤",
    "Giant s Causeway": "巨人堤",
    "Giant's Causeway": "巨人堤",
    "Giant_Death_Robot": "末日机甲",
    "Gilgamesh": "吉尔伽美什",
    "Giovanni De Medici": "乔凡尼·德·美第奇",
    "Gitarja": "特丽布瓦娜",
    "Global Warming Mitigation": "全球变暖减缓学",
    "Global_Warming_Mitigation": "全球变暖减缓学",
    "Globalization": "全球化",
    "Gobustan": "戈布斯坦国家公园",
    "God City": "城市守护女神",
    "God Craftsmen": "工匠之神",
    "God Healing": "潮汐女神",
    "God Of City": "城市守护女神",
    "God Of Craftsmen": "工匠之神",
    "God Of Forge": "锻造之神",
    "God Of Healing": "潮汐女神",
    "God Of Open Sky": "天空之神",
    "God Of Sea": "海洋之神",
    "God Of The City": "城市守护女神",
    "God Of The Forge": "锻造之神",
    "God Of The Open Sky": "天空之神",
    "God Of The Sea": "海洋之神",
    "God Of War": "战争之神",
    "God Of War And Plunder": "战争之神",
    "God The City": "城市守护女神",
    "God The Forge": "锻造之神",
    "God The Open Sky": "天空之神",
    "God The Sea": "海洋之神",
    "God War": "战争之神",
    "God War And Plunder": "战争之神",
    "God of Craftsmen": "工匠之神",
    "God of War and Plunder": "战争之神",
    "God of the Forge": "锻造之神",
    "God of the Open Sky": "天空之神",
    "God of the Sea": "海洋之神",
    "Goddess Festivals": "节庆女神",
    "Goddess Fire": "火之女神",
    "Goddess Of Festivals": "节庆女神",
    "Goddess Of Fire": "火之女神",
    "Goddess Of Hunt": "狩猎女神",
    "Goddess Of The Hunt": "狩猎女神",
    "Goddess Of Tides": "潮汐女神",
    "Goddess The Hunt": "狩猎女神",
    "Goddess Tides": "潮汐女神",
    "Goddess of Festivals": "节庆女神",
    "Goddess of Tides": "潮汐女神",
    "Goddess of the Hunt": "狩猎女神",
    "Golden Gate Bridge": "金门大桥",
    "Golf Course": "高尔夫球场",
    "Gorgo": "戈尔戈",
    "Gov Citystates": "外交部",
    "Gov Conquest": "军阀宝座",
    "Gov Culture": "国家历史博物馆",
    "Gov Faith": "骑士团长礼拜堂",
    "Gov Military": "作战部",
    "Gov Science": "皇家学会",
    "Gov Spies": "情报局",
    "Gov Tall": "谒见厅",
    "Gov Wide": "祠堂",
    "Government": "市政广场",
    "Grace Hopper": "葛丽丝·霍普",
    "Gran Colombia": "大哥伦比亚",
    "Gran Colombia Simon Bolivar": "大哥伦比亚 西蒙·玻利瓦尔",
    "Gran Colombia Simón Bolívar": "大哥伦比亚 西蒙·玻利瓦尔",
    "Granada": "格拉纳达",
    "Granada Frontend": "格拉纳达",
    "Granary": "粮仓",
    "Grand Bazaar": "大巴扎",
    "Grand Master S Chapel": "骑士团长礼拜堂",
    "Grand Master s Chapel": "骑士团长礼拜堂",
    "Grand Master's Chapel": "骑士团长礼拜堂",
    "Grand Mesa": "大平顶山",
    "Grand Visier": "大维齐尔",
    "Great Admiral": "海军统帅",
    "Great Artist": "大艺术家",
    "Great Barrier Reef": "大堡礁",
    "Great Bath": "大浴场",
    "Great Engineer": "大工程师",
    "Great General": "大将军",
    "Great Library": "大图书馆",
    "Great Lighthouse": "大灯塔",
    "Great Merchant": "大商人",
    "Great Musician": "大音乐家",
    "Great Prophet": "大预言家",
    "Great Scientist": "大科学家",
    "Great Wall": "长城",
    "Great Writer": "大作家",
    "Great Zimbabwe": "大津巴布韦",
    "Greece": "希腊",
    "Greece Gorgo": "希腊 戈尔戈",
    "Greece Pericles": "希腊 伯里克利",
    "Greek Hoplite": "重装步兵",
    "Grove": "古树林",
    "Guidance Systems": "制导系统",
    "Guidance_Systems": "制导系统",
    "Guilds": "公会",
    "Gunpowder": "火药",
    "Gurdwara": "谒师所",
    "Guru": "上师",
    "Gustav Klimt": "古斯塔夫·克里姆特",
    "Gustave Eiffel": "古斯塔夫·埃菲尔",
    "Gustavus Adolphus": "古斯塔夫·阿道弗斯",
    "Ha Long Bay": "下龙湾",
    "Hacienda": "大庄园",
    "Hagia Sophia": "圣索菲亚大教堂",
    "Haji Huud": "哈吉·洪德",
    "Halicarnassus Mausoleum": "摩索拉斯王陵墓",
    "Hammurabi": "汉谟拉比",
    "Hangar": "机库",
    "Hanging Gardens": "空中花园",
    "Hannibal Barca": "汉尼拔·巴卡",
    "Hanno Navigator": "航海家汉诺",
    "Hanno The Navigator": "航海家汉诺",
    "Hansa": "商业同业工会",
    "Harald Alt": "哈拉尔德·哈德拉达（瓦良格）",
    "Harbor": "港口",
    "Hardrada Original": "哈拉尔德·哈德拉达（北境王）",
    "Hasegawa Tohaku": "长谷川等伯",
    "Hattusa": "哈图沙",
    "Head Falconer": "首席驯鹰师",
    "Heavy Chariot": "重型战车",
    "Heavy_Chariot": "重型战车",
    "Helena Rubinstein": "海伦娜·鲁宾斯坦",
    "Helicopter": "直升飞机",
    "Hermitage": "艾尔米塔什博物馆",
    "Hetairoi": "伙友骑兵",
    "Hg Wells": "赫伯特·乔治·威尔斯",
    "Hieronymus Bosch": "耶罗尼米斯·博斯",
    "Highlander": "高地军团",
    "Hildegard Bingen": "宾根的希尔德加德",
    "Hildegard Of Bingen": "宾根的希尔德加德",
    "Himerios": "希米里奥斯",
    "Hippodrome": "跑马场",
    "Hojo": "北条时宗",
    "Holy Order": "神圣采购",
    "Holy Site": "圣地",
    "Holy Waters": "神圣水域",
    "Homer": "荷马",
    "Hong Kong": "香港",
    "Hoplite": "重装步兵",
    "Horatio Nelson": "霍雷肖·纳尔逊",
    "Horseback Riding": "骑马",
    "Horseback_Riding": "骑马",
    "Horseman": "骑手",
    "Huey Teocalli": "休伊神庙",
    "Hul Che": "投枪手",
    "Hul che": "投枪手",
    "Hul'che": "投枪手",
    "Humanism": "人文主义",
    "Hungary": "匈牙利",
    "Hungary Black Army": "黑军",
    "Hungary Huszar": "骠骑兵",
    "Hungary Matthias Corvinus": "匈牙利 匈雅提·马加什",
    "Hunter S House": "猎人小屋",
    "Hunter s House": "猎人小屋",
    "Hunter's House": "猎人小屋",
    "Hunza": "罕萨",
    "Hunza Frontend": "罕萨",
    "Huszar": "骠骑兵",
    "Huszár": "骠骑兵",
    "Hwacha": "火车",
    "Hydroelectric Dam": "水电站坝",
    "Hypaspist": "持盾护卫",
    "Hypatia": "希帕蒂娅",
    "Hạ Long Bay": "下龙湾",
    "ICON AMENITIES": "大维齐尔",
    "ICON ANTIAIR LARGE": "无人机防空",
    "ICON BOMBARD": "先进测距",
    "ICON CITIZEN": "卡斯-奥达-巴什",
    "ICON CULTURE": "大主教",
    "ICON DISTRICT": "住房扩建",
    "ICON ENVOY": "初来乍到",
    "ICON FAITH": "主保圣人",
    "ICON FAVOR": "统御诸王",
    "ICON FOOD": "农业发展",
    "ICON GOLD": "掠夺",
    "ICON GREATPERSON": "拨款",
    "ICON GREATPROPHET": "神之堡垒",
    "ICON MOVEMENT": "增强机动",
    "ICON PRODUCTION": "帕夏",
    "ICON PROMOTION": "军备竞赛倡导者",
    "ICON RANGE": "远程",
    "ICON RANGED": "粒子束攻城巨炮",
    "ICON RELIGION": "辩论者",
    "ICON SCIENCE": "尤里卡",
    "ICON STRENGTH": "强力装甲",
    "ICON TOURISM": "策展人",
    "ICON TRADEROUTE": "伟大之爪的崩殂",
    "ICON_AMENITIES": "大维齐尔",
    "ICON_ANTIAIR_LARGE": "无人机防空",
    "ICON_BOMBARD": "先进测距",
    "ICON_CITIZEN": "卡斯-奥达-巴什",
    "ICON_CULTURE": "大主教",
    "ICON_DISTRICT": "住房扩建",
    "ICON_ENVOY": "初来乍到",
    "ICON_FAITH": "主保圣人",
    "ICON_FAVOR": "统御诸王",
    "ICON_FOOD": "农业发展",
    "ICON_GOLD": "掠夺",
    "ICON_GREATPERSON": "拨款",
    "ICON_GREATPROPHET": "神之堡垒",
    "ICON_MOVEMENT": "增强机动",
    "ICON_PRODUCTION": "帕夏",
    "ICON_PROMOTION": "军备竞赛倡导者",
    "ICON_RANGE": "远程",
    "ICON_RANGED": "粒子束攻城巨炮",
    "ICON_RELIGION": "辩论者",
    "ICON_SCIENCE": "尤里卡",
    "ICON_STRENGTH": "强力装甲",
    "ICON_TOURISM": "策展人",
    "ICON_TRADEROUTE": "伟大之爪的崩殂",
    "Ibn Fadlan": "伊本·法德兰",
    "Ibn Khaldun": "伊本·赫勒敦",
    "Ibrahim": "易卜拉欣",
    "Ice Hockey Rink": "冰球场",
    "Icon Amenities": "大维齐尔",
    "Icon Antiair Large": "无人机防空",
    "Icon Bombard": "先进测距",
    "Icon Citizen": "卡斯-奥达-巴什",
    "Icon Culture": "大主教",
    "Icon District": "住房扩建",
    "Icon Envoy": "初来乍到",
    "Icon Faith": "主保圣人",
    "Icon Favor": "统御诸王",
    "Icon Food": "农业发展",
    "Icon Gold": "掠夺",
    "Icon Greatperson": "拨款",
    "Icon Greatprophet": "神之堡垒",
    "Icon Movement": "增强机动",
    "Icon Production": "帕夏",
    "Icon Promotion": "军备竞赛倡导者",
    "Icon Range": "远程",
    "Icon Ranged": "粒子束攻城巨炮",
    "Icon Religion": "辩论者",
    "Icon Science": "尤里卡",
    "Icon Strength": "强力装甲",
    "Icon Tourism": "策展人",
    "Icon Traderoute": "伟大之爪的崩殂",
    "Ideology": "意识形态",
    "Ik Kil": "伊卡-吉尔地下水坑",
    "Ik-Kil": "伊卡-吉尔地下水坑",
    "Ik-kil": "伊卡-吉尔地下水坑",
    "Ikanda": "伊坎达",
    "Imhotepi": "伊姆霍特普",
    "Immortal": "长生军",
    "Impi": "班图武士",
    "Inca": "印加",
    "Inca Pachacuti": "印加 帕查库特克",
    "Inca Warakaq": "瓦剌卡战士",
    "India": "印度",
    "India Chandragupta": "印度 旃陀罗笈多",
    "India Gandhi": "印度 甘地",
    "Indian Varu": "战象",
    "Indonesia": "印度尼西亚",
    "Indonesia Gitarja": "印度尼西亚 特丽布瓦娜",
    "Indonesian Jong": "戎克船",
    "Industrial Era": "工业时代",
    "Industrial Zone": "工业区",
    "Industrialization": "工业化",
    "Infantry": "步兵",
    "Information Era": "信息时代",
    "Information Warfare": "信息战",
    "Information_Warfare": "信息战",
    "Initiation Rites": "启蒙会",
    "Inquisitor": "审判官",
    "Intelligence Agency": "情报局",
    "Irenaeus": "爱任纽",
    "Irene Athens": "伊琳娜女皇",
    "Irene Of Athens": "伊琳娜女皇",
    "Iron Working": "炼铁术",
    "Iron_Working": "炼铁术",
    "Ironclad": "装甲舰",
    "Irrigation": "灌溉",
    "Isaac Newton": "艾萨克·牛顿",
    "Isidore Miletus": "米利都的伊西多尔",
    "Isidore Of Miletus": "米利都的伊西多尔",
    "Itinerant Preachers": "巡回传教士",
    "Jadwiga": "雅德维加",
    "Jahazi": "方舟",
    "Jakob Fugger": "雅各布·富格尔",
    "James Joyce": "詹姆斯·乔伊斯",
    "James Of St George": "圣乔治·詹姆斯",
    "James St George": "圣乔治·詹姆斯",
    "James Watt": "詹姆斯·瓦特",
    "James Young": "詹姆斯·杨",
    "Jamsetji Tata": "贾姆希德吉·塔塔",
    "Janaki Ammal": "佳纳克伊·安马尔",
    "Jane Austen": "简·奥斯汀",
    "Jane Drew": "简·德鲁",
    "Jang Seung Eop": "张承业",
    "Janissary": "苏丹亲兵",
    "Japan": "日本",
    "Japan Hojo Tokimune": "日本 北条时宗",
    "Japan Tokugawa": "日本 德川家康",
    "Japanese Samurai": "武士",
    "Jayavarman": "阇耶跋摩七世",
    "Jebel Barkal": "博尔戈尔山",
    "Jerusalem": "耶路撒冷",
    "Jesuit Education": "耶稣会教育",
    "Jet Bomber": "喷气式轰炸机",
    "Jet Fighter": "喷气式战斗机",
    "Jet_Bomber": "喷气式轰炸机",
    "Jet_Fighter": "喷气式战斗机",
    "Jfd Olympias": "奥林匹娅斯",
    "Joan Arc": "圣女贞德",
    "Joan Of Arc": "圣女贞德",
    "Joao III": "若昂三世",
    "Joao Iii": "若昂三世",
    "Joaquim Marques Lisboa": "若阿金·马奎斯·葡京",
    "Johann Sebastian Bach": "约翰·塞巴斯蒂安·巴赫",
    "Johann Wolfgang Von Goethe": "约翰·沃尔夫冈·冯·歌德",
    "Johannesburg": "约翰内斯堡",
    "Johannesburg Frontend": "约翰内斯堡",
    "John A Roebling": "约翰•罗布尔",
    "John Baptist": "施洗者约翰",
    "John Curtin": "约翰·科廷",
    "John Jacob Astor": "约翰·雅各·阿斯特",
    "John Monash": "约翰·莫纳什",
    "John Rockefeller": "约翰·洛克菲勒",
    "John The Baptist": "施洗者约翰",
    "Jong": "戎克船",
    "Jose De San Martin": "何塞·德·圣马丁",
    "Joseph Paxton": "约瑟夫·帕克斯顿",
    "Julius Caesar": "尤里乌斯·凯撒",
    "Just War": "十字军",
    "Juventino Rosas": "胡文蒂诺·罗萨斯",
    "Kabul": "喀布尔",
    "Kamal Ud Din Behzad": "卡马尔·乌丁·贝赫扎德",
    "Kampung": "甘榜屋",
    "Kandy": "康提",
    "Karel Capek": "卡雷尔·恰佩克",
    "Katsushika Hokusai": "葛饰北斋",
    "Kenzo Tange": "丹下健三",
    "Keshig": "怯薛歹",
    "Khass Oda Bashi": "卡斯-奥达-巴什",
    "Khevsur": "赫雷苏维季战士",
    "Khmer": "高棉",
    "Khmer Domrey": "高棉战象",
    "Khmer Jayavarman VII": "高棉 阇耶跋摩七世",
    "Kilwa Kisiwani": "基尔瓦基斯瓦尼",
    "Knight": "骑士",
    "Kongo": "刚果",
    "Kongo Mvemba A Nzinga": "刚果 姆本巴·恩津加",
    "Kongo Mvemba a Nzinga": "刚果 姆本巴·恩津加",
    "Kongo Nzinga Mbande": "刚果 恩津加·姆班德",
    "Kongo Shield Bearer": "奥姆本巴",
    "Korea": "朝鲜",
    "Korea Sejong": "朝鲜 世宗大王",
    "Korea Seondeok": "朝鲜 善德",
    "Korean Hwacha": "火车",
    "Kotoku In": "高德院",
    "Kotoku in": "高德院",
    "Kotoku-in": "高德院",
    "Krakatoa": "喀拉喀托火山",
    "Kristina": "克里斯蒂娜",
    "Kublai Khan": "忽必烈（蒙古）",
    "Kublai Khan C": "忽必烈（中国）",
    "Kumasi": "库马西",
    "Kupe": "库佩",
    "Kurgan": "坟墩",
    "La Venta": "拉文塔",
    "Lady Of Reeds And Marshes": "芦苇和沼泽地里的夫人",
    "Lady Of The Reeds And Marshes": "芦苇和沼泽地里的夫人",
    "Lady Six Sky": "六日夫人",
    "Lady The Reeds And Marshes": "芦苇和沼泽地里的夫人",
    "Lady Trieu": "赵夫人",
    "Lady of the Reeds and Marshes": "芦苇和沼泽地里的夫人",
    "Lahore": "拉合尔",
    "Lahore Frontend": "拉合尔",
    "Lahore Nihang": "尼杭战士",
    "Lake Retba": "玫瑰湖",
    "Lake Victoria": "维多利亚湖",
    "Lakes Of Ounianga": "乌尼昂加湖泊群",
    "Lakes Ounianga": "乌尼昂加湖泊群",
    "Lakes of Ounianga": "乌尼昂加湖泊群",
    "Laozi": "老子",
    "Lasers": "激光",
    "Laskarina Bouboulina": "拉斯喀瑞尼亚·鲍勃里斯",
    "Laurier": "威尔弗里德·劳雷尔",
    "Lautaro": "莱夫扎茹",
    "Lavra": "拉夫拉修道院",
    "Lay Ministry": "民间宗教团",
    "Legion": "罗马军团",
    "Leif Erikson": "雷夫·埃里克森",
    "Lencois Maranhenses": "拉克伊斯·马拉赫塞斯国家公园",
    "Lençóis Maranhenses": "拉克伊斯·马拉赫塞斯国家公园",
    "Leo Tolstoy": "列夫·托尔斯泰",
    "Leonardo Da Vinci": "列奥纳多·达·芬奇",
    "Levi Strauss": "李维·史特劳斯",
    "Li Bai": "李白",
    "Liang": "梁",
    "Library": "图书馆",
    "Lighthouse": "灯塔",
    "Liliuokalani": "利留卡拉尼",
    "Lime Phoe Ahiram": "阿希拉姆",
    "Lime Teo Owl": "特奥蒂瓦坎 掷矛者猫头鹰",
    "Lime Teo Owl Emissary": "西雅赫·卡克",
    "Lime Teo Owl Warrior": "羽甲战士",
    "Lime Teo Tollan": "波奇特卡聚集区",
    "Lime Thule": "图勒",
    "Lime Thule Dave": "基维乌克",
    "Lime Thule Dogsled": "雪橇猎人",
    "Lime Thule Wbh": "猎人小屋",
    "Line Infantry": "线列步兵",
    "Line_Infantry": "线列步兵",
    "Lisbon": "摩加迪沙",
    "Liu Tianhua": "刘天华",
    "Ll Tekinich II": "特·基尼奇二世",
    "Llanero": "牛仔骑兵",
    "Local Informants": "本地线人",
    "Ludwig": "路德维希二世",
    "Ludwig Van Beethoven": "路德维希·凡·贝多芬",
    "Lumber Mill": "伐木场",
    "Lysefjord": "吕瑟峡湾",
    "Macedon": "马其顿",
    "Macedon Alexander": "马其顿 亚历山大",
    "Macedon Olympias": "马其顿 奥林匹娅斯",
    "Macedonian Hetairoi": "伙友骑兵",
    "Macedonian Hypaspist": "持盾护卫",
    "Machine Gun": "机关枪队",
    "Machine_Gun": "机关枪队",
    "Machinery": "机械",
    "Machu Picchu": "马丘比丘",
    "Madhva Acharya": "摩陀婆·阿查里雅",
    "Madrasa": "伊斯兰学校",
    "Magnus": "马格努斯",
    "Mahabodhi Temple": "摩诃菩提寺",
    "Mahavihara": "大寺",
    "Mali": "马里",
    "Mali Mandekalu Cavalry": "曼德卡鲁骑兵",
    "Mali Mansa Musa": "马里 曼沙·穆萨",
    "Mali Sundiata Keita": "马里 松迪亚塔·凯塔",
    "Malon Raider": "装甲突袭骑兵",
    "Malon_Raider": "装甲突袭骑兵",
    "Malón Raider": "装甲突袭骑兵",
    "Malón_Raider": "装甲突袭骑兵",
    "Mamluk": "奴隶兵",
    "Man At Arms": "披甲战士",
    "Man-At-Arms": "披甲战士",
    "Man-at-arms": "披甲战士",
    "Mandekalu Cavalry": "曼德卡鲁骑兵",
    "Mandekalu_Cavalry": "曼德卡鲁骑兵",
    "Mansa Musa": "曼沙·穆萨",
    "Maori": "毛利",
    "Maori Kupe": "毛利 库佩",
    "Maori Pa": "帕堡",
    "Maori Toa": "托阿勇士",
    "Mapuche": "马普切",
    "Mapuche Lautaro": "马普切 莱夫扎茹",
    "Mapuche Malon Raider": "装甲突袭骑兵",
    "Marae": "毛利会堂",
    "Marco Polo": "马可波罗",
    "Marcus Licinius Crassus": "马库斯·李锡尼·克拉苏",
    "Margaret Cavendish": "玛格丽特·卡文迪什",
    "Margaret Mead": "玛格丽特·米德",
    "Marie Anne Collot": "玛丽安妮·科洛",
    "Marie Catherine D Aulnoy": "玛丽-凯瑟琳·奥诺伊",
    "Marina Raskova": "玛丽娜·拉斯科娃",
    "Mark Twain": "马克·吐温",
    "Market": "市场",
    "Martin Luther": "马丁·路德",
    "Mary Cassatt": "玛丽·卡萨特",
    "Mary Katherine Goddard": "玛丽·凯瑟琳·戈达德",
    "Mary Leakey": "玛丽·利基",
    "Mary Shelley": "玛丽·雪莱",
    "Maryannu Chariot Archer": "世袭贵族战车射手",
    "Maryannu_Chariot_Archer": "世袭贵族战车射手",
    "Masaru Ibuka": "井深大",
    "Masonry": "砌砖",
    "Mass Media": "大众媒体",
    "Mass Production": "批量生产",
    "Mass_Media": "大众媒体",
    "Mass_Production": "批量生产",
    "Mathematics": "数学",
    "Mato Tipila": "魔鬼塔",
    "Matterhorn": "马特洪峰",
    "Matthew Perry": "马休·佩里",
    "Matthias Corvinus": "匈雅提·马加什",
    "Mausoleum At Halicarnassus": "摩索拉斯王陵墓",
    "Mausoleum at Halicarnassus": "摩索拉斯王陵墓",
    "Maya": "玛雅",
    "Maya Lady Six Sky": "玛雅 六日夫人",
    "Maya Te K Inich II": "玛雅 特·基尼奇二世",
    "Maya Te K inich II": "玛雅 特·基尼奇二世",
    "Maya Te' K'inich II": "玛雅 特·基尼奇二世",
    "Mayan Hulche": "投枪手",
    "Mbanza": "姆班赞",
    "Mechanized Infantry": "机械化步兵",
    "Mechanized_Infantry": "机械化步兵",
    "Medic": "医疗兵",
    "Medieval Era": "中世纪",
    "Medieval Faires": "中世纪集市",
    "Medieval Walls": "中世纪城墙",
    "Medieval_Faires": "中世纪集市",
    "Meenakshi Temple": "米纳克希神庙",
    "Meeting House": "礼拜堂",
    "Mekewap": "棚屋",
    "Menelik": "孟尼利克二世",
    "Mercantilism": "重商主义",
    "Mercenaries": "雇佣兵",
    "Merchant": "大商人",
    "Merchant Contractor": "发包人",
    "Merchant Curator": "策展人",
    "Merchant Forestry Management": "林业管理",
    "Merchant Harbormaster": "港务局长",
    "Merchant Investor": "外汇资金",
    "Merchant Land Acquisition": "土地征用",
    "Merchant Tax Collector": "税务员",
    "Metal Casting": "金属铸造",
    "Metal_Casting": "金属铸造",
    "Mexico City": "墨西哥城",
    "Mexico City Frontend": "墨西哥城",
    "Michelangelo": "米开朗基罗",
    "Miguel De Cervantes": "米格尔·德·塞万提斯",
    "Military Academy": "军事学院",
    "Military Engineer": "军事工程师",
    "Military Engineering": "军事工程学",
    "Military Science": "军事学",
    "Military Tactics": "战术",
    "Military Tradition": "军事传统",
    "Military Training": "军事训练",
    "Military_Engineer": "军事工程师",
    "Military_Engineering": "军事工程学",
    "Military_Science": "军事学",
    "Military_Tactics": "战术",
    "Military_Tradition": "军事传统",
    "Military_Training": "军事训练",
    "Mimar Sinan": "米马尔·希南",
    "Minas Geraes": "米纳斯吉拉斯",
    "Minas_Geraes": "米纳斯吉拉斯",
    "Mine": "矿山",
    "Mining": "采矿业",
    "Missile Cruiser": "导弹巡洋舰",
    "Missile Silo": "导弹发射井",
    "Missile_Cruiser": "导弹巡洋舰",
    "Mission": "传教团",
    "Missionary": "传教士",
    "Missionary Zeal": "传教热忱",
    "Mitla": "米特拉",
    "Moai": "摩艾石像",
    "Mobile SAM": "防空导弹车",
    "Mobile Sam": "防空导弹车",
    "Mobile_SAM": "防空导弹车",
    "Mobilization": "动员",
    "Modern AT": "现代反坦克组",
    "Modern Armor": "现代坦克",
    "Modern At": "现代反坦克组",
    "Modern Era": "现代",
    "Modern_AT": "现代反坦克组",
    "Modern_Armor": "现代坦克",
    "Mogadishu": "摩加迪沙",
    "Mohenjo Daro": "摩亨朱-达罗",
    "Mohenjo-Daro": "摩亨朱-达罗",
    "Mohenjo-daro": "摩亨朱-达罗",
    "Moksha": "莫克夏",
    "Monastery": "修道院",
    "Monastic Isolation": "与世隔绝",
    "Mongolia": "蒙古",
    "Mongolia Genghis Khan": "蒙古 成吉思汗",
    "Mongolia Kublai Khan (Mongolia)": "蒙古 忽必烈（蒙古）",
    "Mongolia Kublai Khan (mongolia)": "蒙古 忽必烈（蒙古）",
    "Mongolian Keshig": "怯薛歹",
    "Mont St Michel": "圣米歇尔山",
    "Mont St. Michel": "圣米歇尔山",
    "Montezuma": "蒙特祖玛",
    "Monument": "纪念碑",
    "Monument To Gods": "主神纪念碑",
    "Monument To The Gods": "主神纪念碑",
    "Monument to the Gods": "主神纪念碑",
    "Mosi Oa Tunya": "莫西奥图尼亚瀑布",
    "Mosi oa Tunya": "莫西奥图尼亚瀑布",
    "Mosi-oa-Tunya": "莫西奥图尼亚瀑布",
    "Mosi-oa-tunya": "莫西奥图尼亚瀑布",
    "Mosque": "清真寺",
    "Motlatse Canyon": "布莱德河峡谷",
    "Mound": "卡霍基亚土墩",
    "Mount Everest": "珠穆朗玛峰",
    "Mount Kailash": "冈仁波齐峰",
    "Mount Kilimanjaro": "乞力马扎罗山",
    "Mount Roraima": "罗赖马山",
    "Mount Sinai": "西奈山",
    "Mount Vesuvius": "维苏威火山",
    "Mountain Road": "印加路网",
    "Mountain Tunnel": "穿山隧道",
    "Mountie": "皇家骑警",
    "Murasaki Shikibu": "紫式部",
    "Muscat": "马斯喀特",
    "Muscat Frontend": "马斯喀特",
    "Museum Art": "艺术博物馆",
    "Museum Artifact": "考古博物馆",
    "Musician": "大音乐家",
    "Musketman": "火枪手",
    "Mvemba": "姆本巴·恩津加",
    "Mykola Leontovych": "尼古拉·李森科",
    "Mysticism": "神秘主义",
    "Māori Kupe": "毛利 库佩",
    "Nader Shah": "纳迪尔沙阿",
    "Nalanda": "那烂陀",
    "Nalanda Frontend": "那烂陀",
    "Namib Sand Sea": "纳米布沙漠",
    "Nan Madol": "南马都尔",
    "Nanotechnology": "纳米技术",
    "Napoleon Bonaparte": "拿破仑·波拿巴",
    "National History Museum": "国家历史博物馆",
    "Nationalism": "民族主义",
    "Natural History": "自然历史",
    "Natural_History": "自然历史",
    "Nau": "克拉克帆船",
    "Naval Tradition": "海军传统",
    "Naval_Tradition": "海军传统",
    "Navigation School": "航海学校",
    "Nazca": "纳斯卡",
    "Nazca Frontend": "纳斯卡",
    "Nazca Line": "纳斯卡巨画",
    "Near Future Governance": "近未来治理",
    "Near_Future_Governance": "近未来治理",
    "Neighborhood": "社区",
    "Netherlands": "荷兰",
    "Netherlands Wilhelmina": "荷兰 威廉明娜",
    "Ngao Mbeba": "奥姆本巴",
    "Ngao_Mbeba": "奥姆本巴",
    "Ngazargamu": "纳札加姆",
    "Ngazargamu Frontend": "纳札加姆",
    "Niccolo Machiavelli": "尼可罗·马基亚维利",
    "Nihang": "尼杭战士",
    "Nikola Tesla": "尼古拉·特斯拉",
    "Norway": "挪威",
    "Norway Harald Hardrada (Konge)": "挪威 哈拉尔德·哈德拉达（北境王）",
    "Norway Harald Hardrada (Varangian)": "挪威 哈拉尔德·哈德拉达（瓦良格）",
    "Norway Harald Hardrada (konge)": "挪威 哈拉尔德·哈德拉达（北境王）",
    "Norway Harald Hardrada (varangian)": "挪威 哈拉尔德·哈德拉达（瓦良格）",
    "Norwegian Berserker": "狂暴武士",
    "Norwegian Longship": "维京长船",
    "Nubia": "努比亚",
    "Nubia Amanitore": "努比亚 阿曼妮托尔",
    "Nubian Pitati": "皮塔提弓箭手",
    "Nubian Pyramid": "努比亚金字塔",
    "Nuclear Fission": "核裂变",
    "Nuclear Fusion": "核聚变",
    "Nuclear Power Plant": "核电站",
    "Nuclear Program": "核计划",
    "Nuclear Submarine": "核潜艇",
    "Nuclear_Fission": "核裂变",
    "Nuclear_Fusion": "核聚变",
    "Nuclear_Program": "核计划",
    "Nuclear_Submarine": "核潜艇",
    "Nzinga Mbande": "恩津加·姆班德",
    "O No Yasumaro": "太安万侣",
    "Observation Balloon": "观测气球",
    "Observation_Balloon": "观测气球",
    "Observatory": "天文台",
    "Offshore Oil Rig": "海上石油钻机",
    "Offshore Wind Farm": "离岸风力发电厂",
    "Offworld Mission": "外星任务",
    "Offworld_Mission": "外星任务",
    "Oil Power Plant": "燃油发电厂",
    "Oil Well": "油井",
    "Okihtcitaw": "奥克奇塔乌",
    "Old Faithful": "老实泉",
    "Omar Khayyam": "奥马尔·海亚姆",
    "Onager": "野驴",
    "Open Air Museum": "生态博物馆",
    "Open-Air Museum": "生态博物馆",
    "Open-air Museum": "生态博物馆",
    "Opera And Ballet": "歌剧和芭蕾",
    "Opera Ballet": "歌剧和芭蕾",
    "Opera and Ballet": "歌剧和芭蕾",
    "Opera_and_Ballet": "歌剧和芭蕾",
    "Oppidum": "奥皮杜姆",
    "Optimization Imperative": "最优化命令",
    "Optimization_Imperative": "最优化命令",
    "Oracle": "神谕",
    "Ordu": "斡耳朵",
    "Oromo Cavalry": "奥罗莫骑兵",
    "Oromo_Cavalry": "奥罗莫骑兵",
    "Orszaghaz": "匈牙利议会大厦",
    "Országház": "匈牙利议会大厦",
    "Ottoman": "奥斯曼",
    "Ottoman Barbary Corsair": "巴巴里海盗",
    "Ottomans Suleiman (Kanuni)": "奥斯曼 苏莱曼一世（立法者）",
    "Ottomans Suleiman (Muhtesem)": "奥斯曼 苏莱曼一世（大帝）",
    "Ottomans Suleiman (Muhteşem)": "奥斯曼 苏莱曼一世（大帝）",
    "Ottomans Suleiman (kanuni)": "奥斯曼 苏莱曼一世（立法者）",
    "Ottomans Suleiman (muhtesem)": "奥斯曼 苏莱曼一世（大帝）",
    "Outback Station": "内陆牧场",
    "Ovid": "奥维德",
    "Oxford University": "牛津大学",
    "P 51 Mustang": "P-51战斗机",
    "P 51_Mustang": "P-51战斗机",
    "P-51 Mustang": "P-51战斗机",
    "P-51_Mustang": "P-51战斗机",
    "Pa": "帕堡",
    "Pachacuti": "帕查库特克",
    "Pagoda": "宝塔",
    "Pairidaeza": "波斯庭院",
    "Paititi": "帕依提提",
    "Palace": "宫殿",
    "Palenque Frontend": "米特拉",
    "Palgum": "沟渠",
    "Pamukkale": "棉花堡",
    "Panama Canal": "巴拿马运河",
    "Pantanal": "潘塔纳尔湿地",
    "Papal Primacy": "教皇权威",
    "Parks Recreation": "公园与休憩",
    "Pasha": "帕夏",
    "Pasture": "牧场",
    "Païtiti": "帕依提提",
    "Pedro": "佩德罗二世",
    "Pericles": "伯里克利",
    "Persia": "波斯",
    "Persia Cyrus": "波斯 居鲁士",
    "Persia Nader Shah": "波斯 纳迪尔沙阿",
    "Persian Immortal": "长生军",
    "Peter Great": "彼得",
    "Peter Ilyich Tchaikovsky": "彼得·伊里奇·柴可夫斯基",
    "Petra": "佩特拉古城",
    "Philip II": "菲利普二世",
    "Philip Ii": "菲利普二世",
    "Phoenicia": "腓尼基",
    "Phoenicia Ahiram": "腓尼基 阿希拉姆",
    "Phoenicia Bireme": "双层桨座战船",
    "Phoenicia Dido": "腓尼基 狄多",
    "Piero De Bardi": "皮耶罗·迪·巴尔迪",
    "Pike And Shot": "枪刺与射击方阵",
    "Pike and Shot": "枪刺与射击方阵",
    "Pike_and_Shot": "枪刺与射击方阵",
    "Pikeman": "长矛兵",
    "Pilgrimage": "朝圣",
    "Pillar Tomb": "柱墓",
    "Pingala": "平伽拉",
    "Piopiotahi": "米尔福德峡湾",
    "Pitati Archer": "皮塔提弓箭手",
    "Pitati_Archer": "皮塔提弓箭手",
    "Plantation": "种植园",
    "Plastics": "塑料",
    "Pochteca Enclave": "波奇特卡聚集区",
    "Poland": "波兰",
    "Poland Jadwiga": "波兰 雅德维加",
    "Polder": "圩田",
    "Polish Hussar": "翼骑兵",
    "Political Philosophy": "政治哲学",
    "Political_Philosophy": "政治哲学",
    "Portugal": "葡萄牙",
    "Portugal Joao III": "葡萄牙 若昂三世",
    "Portugal João III": "葡萄牙 若昂三世",
    "Portuguese Nau": "克拉克帆船",
    "Potala Palace": "布达拉宫",
    "Pottery": "制陶术",
    "Poundmaker": "庞德梅克",
    "Poundmaker Ability": "有利条件",
    "Power Plant Expansion2": "核电站",
    "Prasat": "高棉庙堂",
    "Predictive Systems": "预报系统",
    "Predictive_Systems": "预报系统",
    "Preserve": "保护区",
    "Preslav": "普雷斯拉夫",
    "Printing": "印刷术",
    "Privateer": "私掠船",
    "Professional Sports": "职业体育",
    "Professional_Sports": "职业体育",
    "Prophet": "大预言家",
    "Pyramid": "努比亚金字塔",
    "Pyramids": "金字塔",
    "Pítati Archer": "皮塔提弓箭手",
    "Pítati_Archer": "皮塔提弓箭手",
    "Pā": "帕堡",
    "Qhapaq Nan": "印加路网",
    "Qhapaq Ñan": "印加路网",
    "Qin Alt": "秦始皇（大一统）",
    "Qin Original": "秦始皇（天命者）",
    "Qiu Ying": "仇英",
    "Qu Yuan": "屈原",
    "Quadrireme": "四段帆船",
    "Quarry": "采石场",
    "Queen S Bibliotheque": "女王图书馆",
    "Queen s Bibliotheque": "女王图书馆",
    "Queen's Bibliotheque": "女王图书馆",
    "Queens Bibliotheque": "女王图书馆",
    "Rabindranath Tagore": "拉宾德拉纳特·泰戈尔",
    "Radio": "无线电",
    "Raja Todar Mal": "拉贾·托达·马尔",
    "Rajendra Chola": "拉金德拉·朱罗",
    "Ramses": "拉美西斯二世",
    "Ranger": "游骑兵",
    "Rani Lakshmibai": "詹西女王",
    "Rapa Nui": "拉帕努伊",
    "Rapa Nui Frontend": "拉帕努伊",
    "Rapid Deployment": "紧急部署",
    "Rapid_Deployment": "紧急部署",
    "Recorded History": "历史记录",
    "Recorded_History": "历史记录",
    "Redcoat": "红衫军",
    "Redoubt": "棱堡",
    "Refining": "精炼",
    "Reformed Church": "归正会",
    "Reformed_Church": "归正会",
    "Reinforced Infrastructure": "加固材料",
    "Religious Colonization": "宗教殖民",
    "Religious Community": "宗教社区",
    "Religious Idols": "宗教偶像",
    "Religious Settlements": "宗教移民",
    "Religious Unity": "宗教统一",
    "Reliquaries": "圣物箱",
    "Rembrandt Van Rijn": "伦勃朗·凡·莱因",
    "Renaissance Era": "文艺复兴时期",
    "Renaissance Walls": "文艺复兴城墙",
    "Replaceable Parts": "零件规格化",
    "Replaceable_Parts": "零件规格化",
    "Research Lab": "研究实验室",
    "Resource Manager Black Marketeer": "黑市商人",
    "Resource Manager Expedition": "给养保障",
    "Resource Manager Groundbreaker": "破土者",
    "Resource Manager Industrialist": "实业家",
    "Resource Manager Surplus Logistics": "盈余物流",
    "Resource Manager Vertical Integration": "纵向结合",
    "Reyna": "瑞娜",
    "Rifling": "膛线",
    "River Goddess": "河神",
    "Robert Bruce": "罗伯特一世",
    "Robert Goddard": "罗伯特·哥达德",
    "Robert The Bruce": "罗伯特一世",
    "Robotics": "机器人技术",
    "Rock Gibraltar": "直布罗陀巨岩",
    "Rock Hewn Church": "独石教堂",
    "Rock Of Gibraltar": "直布罗陀巨岩",
    "Rock of Gibraltar": "直布罗陀巨岩",
    "Rock-Hewn Church": "独石教堂",
    "Rock-hewn Church": "独石教堂",
    "Rocket Artillery": "火箭炮",
    "Rocket_Artillery": "火箭炮",
    "Rocketry": "火箭研究",
    "Roman Fort": "古罗马堡垒",
    "Roman Legion": "罗马军团",
    "Roman Onager": "野驴",
    "Rome": "罗马",
    "Rome Julius Caesar": "罗马 尤里乌斯·凯撒",
    "Rome Trajan": "罗马 图拉真",
    "Rough Rider": "莽骑兵",
    "Rough_Rider": "莽骑兵",
    "Royal Navy Dockyard": "皇家海军船坞",
    "Royal Society": "皇家学会",
    "Royal Tomb": "皇家陵墓",
    "Rta Pa": "藏巴弓骑",
    "Rta_Pa": "藏巴弓骑",
    "Ruhr Valley": "鲁尔山谷",
    "Rumi": "鲁米",
    "Russia": "俄罗斯",
    "Russia Peter": "俄罗斯 彼得",
    "Russian Cossack": "哥萨克骑兵",
    "Sabum Kibittum": "主力军团",
    "Sabum_Kibittum": "主力军团",
    "Sacred Path": "神圣道路",
    "Sacred Places": "神圣之地",
    "Sahara El Beyda": "白沙漠",
    "Sahara el Beyda": "白沙漠",
    "Sailing": "航海术",
    "Saka Horse Archer": "萨卡弓骑手",
    "Saka_Horse_Archer": "萨卡弓骑手",
    "Saladin Alt": "萨拉丁（苏丹）",
    "Saladin Original": "萨拉丁（维齐尔）",
    "Salar De Uyuni": "乌尤尼盐沼",
    "Salar de Uyuni": "乌尤尼盐沼",
    "Samarkand": "撒马尔罕",
    "Samarkand Frontend": "撒马尔罕",
    "Samori Ture": "萨摩里·杜尔",
    "Samurai": "武士",
    "Sanctuary": "避难所",
    "Sanitation": "卫生设备",
    "Santa Cruz": "圣·克鲁斯",
    "Sarah Breedlove": "莎拉·布里德洛夫",
    "Satellites": "卫星",
    "Scientific Theory": "科学理论",
    "Scientific_Theory": "科学理论",
    "Scientist": "大科学家",
    "Scorched Earth": "焦土策略",
    "Scorched_Earth": "焦土策略",
    "Scotland": "苏格兰",
    "Scotland Robert Bruce": "苏格兰 罗伯特一世",
    "Scotland Robert The Bruce": "苏格兰 罗伯特一世",
    "Scotland Robert the Bruce": "苏格兰 罗伯特一世",
    "Scott Joplin": "斯科特·乔普林",
    "Scottish Highlander": "高地军团",
    "Scout": "侦察兵",
    "Scripture": "经文",
    "Scythia": "斯基泰",
    "Scythia Tomyris": "斯基泰 托米丽司",
    "Scythian Horse Archer": "萨卡弓骑手",
    "Sea Dog": "海猎犬",
    "Sea_Dog": "海猎犬",
    "Seaport": "码头",
    "Seaside Resort": "海滨度假区",
    "Seastead": "海洋家园",
    "Seasteads": "海洋家园",
    "Sejong": "世宗大王",
    "Seondeok": "善德",
    "Seowon": "书院",
    "Serasker": "塞拉斯克尔",
    "Sergei Korolev": "谢尔盖·科罗廖夫",
    "Sergey Gorshkov": "谢尔盖·戈尔什科夫",
    "Sewer": "下水道",
    "Shah Jahan": "沙贾汉",
    "Shaka": "恰卡",
    "Shipbuilding": "造船术",
    "Shipyard": "造船厂",
    "Shopping Mall": "购物商场",
    "Shrine": "神社",
    "Siddhartha Gautama": "悉达多·乔达摩",
    "Siege Tactics": "攻城术",
    "Siege Tower": "攻城塔",
    "Siege_Tactics": "攻城术",
    "Siege_Tower": "攻城塔",
    "Simon Bolivar": "西蒙·玻利瓦尔",
    "Simon Peter": "西蒙·彼得",
    "Singapore": "新加坡",
    "Singapore Frontend": "新加坡",
    "Ski Resort": "滑雪场",
    "Skirmisher": "散兵",
    "Slinger": "投石兵",
    "Smart Materials": "智能材料",
    "Smart Power Doctrine": "巧实力主义",
    "Smart_Materials": "智能材料",
    "Smart_Power_Doctrine": "巧实力主义",
    "Social Media": "社交媒体",
    "Social_Media": "社交媒体",
    "Sofonisba Anguissola": "索福尼斯巴·安圭索拉",
    "Solar Farm": "太阳能农场",
    "Songtsan Gampo": "松赞干布",
    "Space Race": "太空竞赛",
    "Space_Race": "太空竞赛",
    "Spain": "西班牙",
    "Spain Philip II": "西班牙 菲利普二世",
    "Spanish Conquistador": "征服者",
    "Spearman": "枪兵",
    "Spec Ops": "特种部队",
    "Spec_Ops": "特种部队",
    "Sphinx": "狮身人面像",
    "Square Rigging": "横帆装置",
    "Square_Rigging": "横帆装置",
    "Sri Pada": "亚当峰",
    "St Basil S Cathedral": "圣瓦西里主教座堂",
    "St Basil s Cathedral": "圣瓦西里主教座堂",
    "St Basils Cathedral": "圣瓦西里主教座堂",
    "St. Basil's Cathedral": "圣瓦西里主教座堂",
    "Stable": "马厩",
    "Stadium": "体育场",
    "Stamford Raffles": "斯坦福·莱佛士",
    "Star Fort": "文艺复兴城墙",
    "State Workforce": "国家劳动力",
    "State_Workforce": "国家劳动力",
    "Statue Liberty": "自由女神像",
    "Statue Of Liberty": "自由女神像",
    "Statue Of Zeus": "宙斯像",
    "Statue Zeus": "宙斯像",
    "Statue of Liberty": "自由女神像",
    "Statue of Zeus": "宙斯像",
    "Stave Church": "木板教堂",
    "Stealth Technology": "隐形技术",
    "Stealth_Technology": "隐形技术",
    "Steam Power": "蒸汽动力",
    "Steam_Power": "蒸汽动力",
    "Steel": "钢铁",
    "Stephanie Kwolek": "斯黛芬妮·克劳莱克",
    "Stepwell": "梯井",
    "Stewardship": "管理工作",
    "Stirrups": "马镫",
    "Stock Exchange": "证券交易所",
    "Stone Circles": "石圈",
    "Stonehenge": "巨石阵",
    "Street Carnival": "街头狂欢节",
    "Stupa": "窣堵波",
    "Submarine": "潜艇",
    "Sudirman": "苏迪曼",
    "Suffrage": "选举权",
    "Suguba": "曼丁哥市场",
    "Suk Al Hasan": "哈桑·伊本·苏莱曼",
    "Suk Dzong": "宗堡",
    "Suk Jahazi": "方舟",
    "Suk Pillar Tomb": "柱墓",
    "Suk Swahili": "斯瓦希里",
    "Suk Tibet": "吐蕃",
    "Suk Tibet Rta Pa": "藏巴弓骑",
    "Suk Trisong Detsen": "赤松德赞",
    "Suk Vercingetorix": "维钦托利",
    "Sukiennice": "纺织会馆",
    "Suleiman Alt": "苏莱曼一世（大帝）",
    "Suleiman Janissary": "苏丹亲兵",
    "Suleiman Original": "苏莱曼一世（立法者）",
    "Sumeria": "苏美尔",
    "Sumeria Gilgamesh": "苏美尔 吉尔伽美什",
    "Sumerian War Cart": "战车",
    "Sun Tzu": "孙子",
    "Sundiata Keita": "松迪亚塔·凯塔",
    "Supply Convoy": "补给车队",
    "Supply_Convoy": "补给车队",
    "Swahili Al Hasan Ibn Sulaiman": "斯瓦希里 哈桑·伊本·苏莱曼",
    "Swahili Al Hasan ibn Sulaiman": "斯瓦希里 哈桑·伊本·苏莱曼",
    "Swahili Al-Hasan ibn Sulaiman": "斯瓦希里 哈桑·伊本·苏莱曼",
    "Swahili Al-hasan Ibn Sulaiman": "斯瓦希里 哈桑·伊本·苏莱曼",
    "Sweden": "瑞典",
    "Sweden Carolean": "卡洛林步兵",
    "Sweden Kristina": "瑞典 克里斯蒂娜",
    "Swordsman": "剑客",
    "Sydney Opera House": "悉尼歌剧院",
    "Synagogue": "犹太教堂",
    "Synthetic Materials": "合成材料",
    "Synthetic Technocracy": "最优化命令",
    "Synthetic_Materials": "合成材料",
    "T Roosevelt Original": "泰迪·罗斯福（进步党）",
    "T Roosevelt Roughrider": "泰迪·罗斯福（莽骑兵）",
    "Tagma": "甲胄骑兵",
    "Taj Mahal": "泰姬陵",
    "Tamar": "塔玛丽",
    "Tank": "坦克",
    "Taruga": "塔鲁加",
    "Taruga Frontend": "塔鲁加",
    "Telecommunications": "远程通信",
    "Temple": "寺庙",
    "Temple Artemis": "阿耳忒弥斯神庙",
    "Temple Of Artemis": "阿耳忒弥斯神庙",
    "Temple of Artemis": "阿耳忒弥斯神庙",
    "Teotihuacan Spearthrower Owl": "特奥蒂瓦坎 掷矛者猫头鹰",
    "Teotihuacán Spearthrower Owl": "特奥蒂瓦坎 掷矛者猫头鹰",
    "Terrace Farm": "梯田农场",
    "Terracotta Army": "兵马俑",
    "Thanh": "城池",
    "The Ambassador": "阿玛妮",
    "The Builder": "梁",
    "The Cardinal": "莫克夏",
    "The Defender": "维克多",
    "The Educator": "平伽拉",
    "The Enlightenment": "启蒙运动",
    "The Merchant": "瑞娜",
    "The Resource Manager": "马格努斯",
    "The Wheel": "轮子",
    "The_Enlightenment": "启蒙运动",
    "Theater": "剧院广场",
    "Themistocles": "特米斯托克力",
    "Theodora": "狄奥多拉",
    "Theology": "神学",
    "Thermal Bath": "温泉浴场",
    "Thomas Aquinas": "托马斯·阿奎那",
    "Thule Kiviuq": "图勒 基维乌克",
    "Thành": "城池",
    "Tibet Trisong Detsen": "吐蕃 赤松德赞",
    "Tiger I": "虎式坦克",
    "Tiger_I": "虎式坦克",
    "Timur": "帖木儿",
    "Tithe": "什一税",
    "Titian": "提香",
    "Tlachtli": "蹴球场",
    "Toa": "托阿勇士",
    "Togo Heihachiro": "东乡平八郎",
    "Tokugawa": "德川家康",
    "Tomyris": "托米丽司",
    "Torre De Belem": "贝伦塔",
    "Torre de Belem": "贝伦塔",
    "Torre de Belém": "贝伦塔",
    "Torres Del Paine": "百内国家公园",
    "Torres del Paine": "百内国家公园",
    "Totalitarianism": "极权主义",
    "Trading Dome": "圆顶市集",
    "Trajan": "图拉真",
    "Trebuchet": "投石机",
    "Trung Trac": "征侧",
    "Tsikhe": "堡垒",
    "Tsingy De Bemaraha": "贝马拉哈国家公园",
    "Tsingy de Bemaraha": "贝马拉哈国家公园",
    "Tupac Amaru": "图帕克·阿马鲁",
    "U Boat": "U型潜水艇",
    "U-Boat": "U型潜水艇",
    "U-boat": "U型潜水艇",
    "Ubsunur Hollow": "乌布苏盆地",
    "Uluru": "乌卢鲁",
    "University": "大学",
    "University Of Sankore": "桑科雷大学",
    "University Sankore": "桑科雷大学",
    "University of Sankore": "桑科雷大学",
    "Urbanization": "城市化",
    "Valletta": "瓦莱塔",
    "Valmikiy": "蚁垤",
    "Varu": "战象",
    "Vatican City": "梵蒂冈城",
    "Vatican City Frontend": "梵蒂冈城",
    "Venetian Arsenal": "威尼斯军械库",
    "Venice": "威尼斯",
    "Venture Politics": "政治冒险",
    "Venture_Politics": "政治冒险",
    "Victor": "维克多",
    "Victoria Alt": "维多利亚（蒸汽时代）",
    "Victoria Original": "维多利亚（帝国时代）",
    "Vietnam": "越南",
    "Vietnam Ba Trieu": "越南 赵夫人",
    "Vietnam Bà Triệu": "越南 赵夫人",
    "Vietnamese Voi Chien": "象兵",
    "Vijaya Wimalaratne": "维贾雅·维玛拉拉特",
    "Viking Longship": "维京长船",
    "Viking_Longship": "维京长船",
    "Vilnius": "维尔纽斯",
    "Vincent Van Gogh": "文森特·梵高",
    "Voi Chien": "象兵",
    "Voi Chiến": "象兵",
    "Voi_Chien": "象兵",
    "Voi_Chiến": "象兵",
    "Vredefort Dome": "弗里德堡陨石坑",
    "Walls": "远古城墙",
    "War Cart": "战车",
    "War Department": "作战部",
    "War-Cart": "战车",
    "War-cart": "战车",
    "Warak’aq": "瓦剌卡战士",
    "Warlord S Throne": "军阀宝座",
    "Warlord s Throne": "军阀宝座",
    "Warlord's Throne": "军阀宝座",
    "Warrior": "勇士",
    "Warrior Monk": "武僧",
    "Warrior Monks": "武僧",
    "Warrior_Monk": "武僧",
    "Wassily Kandinsky": "瓦西里·康定斯基",
    "Wat": "佛寺",
    "Water Entertainment Complex": "水上乐园",
    "Water Mill": "水磨",
    "Water Street Carnival Expansion2": "科帕卡瓦纳",
    "Water Works": "住房扩建",
    "Wernher Von Braun": "沃纳·冯·布劳恩",
    "Wheel": "轮子",
    "Wilhelmina": "威廉明娜",
    "William Shakespeare": "威廉·莎士比亚",
    "Wind Farm": "风力发电厂",
    "Winged Hussar": "翼骑兵",
    "Winged_Hussar": "翼骑兵",
    "Wolfgang Amadeus Mozart": "沃尔夫冈·阿马迪斯·莫扎特",
    "Wolin": "沃林",
    "Wolin Frontend": "沃林",
    "Work Ethic": "职业道德",
    "Workshop": "工作坊",
    "World Church": "普世教会",
    "Writer": "大作家",
    "Writing": "写作",
    "Wu Zetian": "武则天",
    "Wulingyuan": "武陵源",
    "Yatsuhashi Kengyo": "八桥检校",
    "Yerevan": "埃里温",
    "Yi Sun Sin": "李舜臣",
    "Yongle": "永乐皇帝",
    "Yosemite": "约塞米蒂国家公园",
    "Zanzibar": "桑给巴尔",
    "Zen Meditation": "禅修",
    "Zhang Heng": "张衡",
    "Zhang Qian": "张骞",
    "Zhangye Danxia": "张掖丹霞",
    "Zheng He": "郑和",
    "Zhou Daguan": "周达观",
    "Ziggurat": "金字形神塔",
    "Zoning Commissioner": "规划委员",
    "Zoo": "动物园",
    "Zoroaster": "琐罗亚斯德",
    "Zulu": "祖鲁",
    "Zulu Impi": "班图武士",
    "Zulu Shaka": "祖鲁 恰卡"
}
